### ISSUE TITLE
I got json instead of csv files!

### ISSUE THREAD

**Issue by danizwam** [hutauf/vine-prices-estimation#2]
Hi,

as described in the title, i have two folders (Retail.OrderHistory.1 and Retail.OrderHistory.2) and they contain json, not csv files.

Does your tool work with json too?

**Comment by hutauf** [comment]
No, but can you attach an anonymous portion of your json, then I might be able to include it as well.

**Comment by danizwam** [comment]
This is a decsription of the json, generated with ChatGPT:

`{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Amazon Orders",
  "description": "List of Amazon orders with details",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "Website": {
        "type": "string",
        "description": "The name of the website from which the order was placed."
      },
      "Order ID": {
        "type": "string",
        "description": "A unique identifier for the order."
      },
      "Order Date": {
        "type": "string",
        "format": "date-time",
        "description": "The date and time when the order was placed."
      },
      "Currency": {
        "type": "string",
        "description": "The currency in which the transaction was made."
      },
      "Unit Price": {
        "type": "number",
        "description": "The cost of a single unit of the product."
      },
      "Unit Price Tax": {
        "type": "number",
        "description": "The amount of tax for the unit price."
      },
      "Shipping Charge": {
        "type": "number",
        "description": "The cost of shipping the product."
      },
      "Total Discounts": {
        "type": "number",
        "description": "The total discounts applied to the order."
      },
      "Total Owed": {
        "type": "number",
        "description": "The total amount owed for the order."
      },
      "ASIN": {
        "type": "string",
        "description": "Amazon Standard Identification Number for the product."
      },
      "Quantity": {
        "type": "integer",
        "description": "The number of units of the product ordered."
      },
      "Shipment Item Subtotal": {
        "type": "string",
        "description": "The subtotal for the shipped item."
      },
      "Shipment Item Subtotal Tax": {
        "type": "string",
        "description": "The amount of tax for the shipped item subtotal."
      },
      "Ship Date": {
        "type": "string",
        "format": "date-time",
        "description": "The date and time when the product was shipped."
      },
      "Product Condition": {
        "type": "string",
        "description": "The condition of the product when shipped."
      },
      "Payment Instrument Type": {
        "type": "string",
        "description": "The type of payment instrument used for the order."
      },
      "Order Status": {
        "type": "string",
        "description": "The status of the order (e.g., Closed, Cancelled)."
      },
      "Shipment Status": {
        "type": "string",
        "description": "The status of the shipment (e.g., Shipped)."
      },
      "Shipping Option": {
        "type": "string",
        "description": "The shipping option that was selected for the delivery."
      },
      "Shipping Address": {
        "type": "string",
        "description": "The address to which the product was shipped."
      },
      "Billing Address": {
        "type": "string",
        "description": "The address associated with the payment method."
      },
      "Carrier Name & Tracking Number": {
        "type": "string",
        "description": "The shipping carrier and the tracking number for the order."
      },
      "Product Name": {
        "type": "string",
        "description": "The name of the product ordered."
      }
    },
    "required": ["Website", "Order ID", "Order Date", "Currency", "Unit Price", "Total Owed", "ASIN", "Quantity", "Order Status", "Shipping Address", "Billing Address", "Product Name"]
  }
}
`
Already shipped:

`{
		"Website": "Amazon.de",
		"Order ID": "111-1111111-1111111",
		"Order Date": "2002-04-10T23:59:35Z",
		"Currency": "EUR",
		"Unit Price": 26.72,
		"Unit Price Tax": 4.27,
		"Shipping Charge": 0.0,
		"Total Discounts": 0.0,
		"Total Owed": 30.99,
		"ASIN": "B123123123",
		"Quantity": 1,
		"Shipment Item Subtotal": "53.44",
		"Shipment Item Subtotal Tax": "8.54",
		"Ship Date": "2002-04-11T14:27:20Z",
		"Order Status": "Closed",
		"Shipment Status": "Shipped",
		"Shipping Address": "Max Mustermann Musterstrasse 6 Musterstadt NRW 12345 Germany",
		"Billing Address": "Max Mustermann Musterstrasse 6 Musterstadt NRW 12345 Germany",
		"Carrier Name & Tracking Number": "Sendungsnummer",
		"Product Name": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
	},
	{
		"Website": "Amazon.de",
		"Order ID": "303-1490093-5217965",
		"Order Date": "2023-10-30T20:59:30Z",
		"Currency": "EUR",
		"Unit Price": 17.64,
		"Unit Price Tax": 3.35,
		"Shipping Charge": 0.0,
		"Total Discounts": 0.0,
		"Total Owed": 20.99,
		"ASIN": "B11231232",
		"Quantity": 1,
		"Shipment Item Subtotal": "17.64",
		"Shipment Item Subtotal Tax": "3.35",
		"Ship Date": "2023-10-31T00:57:04Z",
		"Product Condition": "New",
		"Order Status": "Closed",
		"Shipment Status": "Shipped",
		"Shipping Option": "premium-de",
		"Shipping Address": "Max Mustermann Musterstrasse 6 Musterstadt NRW 12345 Germany",
		"Billing Address": "Max Mustermann Musterstrasse 6 Musterstadt NRW 12345 Germany",
		"Carrier Name & Tracking Number": "asdfasdfasfd",
		"Product Name": "asdfkjalsfdkjals dflasjdf laksdfjadf"
	},`

not shipped:

`{
		"Website": "Amazon.de",
		"Order ID": "0111-1111111-1111111",
		"Order Date": "2023-10-31T10:56:43.006Z",
		"Currency": "EUR",
		"Unit Price": 11.14,
		"Unit Price Tax": 2.12,
		"Shipping Charge": 0.0,
		"Total Discounts": -2.65,
		"Total Owed": 23.87,
		"ASIN": "B123123123",
		"Quantity": 2,
		"Product Condition": "New",
		"Order Status": "Authorized",
		"Shipping Option": "std-sns-de",
		"Shipping Address": "Max Mustermann Musterstrasse 6 Musterstadt NRW 12345 Germany",
		"Billing Address": "Max Mustermann Musterstrasse 6 Musterstadt NRW 12345 Germany",
		"Product Name": "asdfasdkalsdjflajsdflajsdf"
	},`

**Comment by hutauf** [comment]
OK, just to make it clear, you put some part of the json into chatgpt and the first part of your message shows the output of chatgpt. Then you shared two items that have been shipped and one that didn't yet, and those are just copies from your json directly?

Because this looks like the regular "records" schema that a lot of people use to write json and that would be very easy to implement. I will create a branch for you shortly.

**Comment by danizwam** [comment]
> OK, just to make it clear, you put some part of the json into chatgpt and the first part of your message shows the output of chatgpt. Then you shared two items that have been shipped and one that didn't yet, and those are just copies from your json directly?
> 
> Because this looks like the regular "records" schema that a lot of people use to write json and that would be very easy to implement. I will create a branch for you shortly.

Yes, that's correct ;)

**Comment by hutauf** [comment]
I'm currently not at home and coded the update on my smartphone.. Not sure if that works. But I can't test it anyway as I don't have your json file. Can you test it? I created a new branch for your issue. Are you familiar with that and can you download and try the update?

**Comment by oobyx** [comment]
I've tried it:

>>> download_data.py /Users/macos/Downloads/Amazon/retail.json
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'download_data' is not defined

**Comment by hutauf** [comment]
> I've tried it:
> 
> > > > download_data.py /Users/macos/Downloads/Amazon/retail.json
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > NameError: name 'download_data' is not defined

Hey, thanks a lot for trying it. Can you please execute the code from a regular command line / terminal and not from within python?

For example, in a regular terminal run the command "python download_data.py path_to_json.json".

Otherwise python tries to access a variable with the name of the file and that's not gonna work.

**Comment by oobyx** [comment]
Was my fault. There was some missing modules.  Now it works

**Comment by hutauf** [comment]
Is it working now? If so, I would close the issue.

**Comment by oobyx** [comment]
Yes! Thank you very much for this script!

**Comment by oobyx** [comment]
One question: Does the script pull the latest price or the order date price?

**Comment by hutauf** [comment]
It tries to pull both informations, but for me some product don't have any price (sometimes amazon even actively blocks keepa from tracking some products) and sometimes keepa doesn't have a record from the time you ordered.
