### ISSUE TITLE
Delisted ASINs

### ISSUE THREAD

**Issue by torbendury** [hutauf/vine-prices-estimation#4]
Hi,

I just saw your tool and was quite happy about someone sharing an option to get clarification on probable price ranges for Vine products.

A question before I try it myself: Does it also handle delisted ASINs? I tried scraping a friend's account with selenium in a similar way (directly from the Vine page, not via GDPR request) and crawling today's prices from Amazon directly - and found lots of products which are not only "Currently Unavailable" but can not be found anymore at all.

I didn't know about "keepa" until now, so it would be very interesting to see information about this kind of product.

I'd happily share my implementation too, if it is of any interest.

**Comment by hutauf** [comment]
If there are historic prices, you can get them of course from keepa. Otherwise, it can happen that there are no prices available ever and you can still order stuff from Amazon vine.. Then you have no clue what's going on..

Using selenium on Amazon directly can possibly get you kicked out of vine.

You can search for the ASIN directly on keepa also without this tool here.

If you want to I would be happy to see your approach, maybe I can learn something from it.

**Comment by torbendury** [comment]
Thanks for the hint on getting kicked out, which isn't that much of a problem for my friends case. Anyway, working around it with different user agents and a reasonable amount of traffic seems to do the trick.

I'll rework my script and publish it afterwards. I'll also have a look at keepa as soon as I find time.

**Comment by torbendury** [comment]
@hutauf it seems like there are indeed products which are available for Vine testers, but were never available for sale and simply disappeared - which is what I guess where you take your `random_magic_number` for :-)

Anyway, I just published my code on [torbendury/vinelist-py](https://github.com/torbendury/vinelist-py) which is open for your review. I didn't find time yet to polish it but it should do the trick.

**Comment by hutauf** [comment]
Thanks for sharing. I quickly checked your code. It's very well written and easy to understand and follow. Maybe it will come in handy at some point.

I'll close this issue, but feel free to reopen or create a new one if required.
